version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  server:
    build: .
    ports:
      - '${PORT:-5000}:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/roblox
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SCHEMA_VERSION=${SCHEMA_VERSION}
      - PORT=5000
      - ALLOWED_IPS=${ALLOWED_IPS}
    depends_on:
      - mongo
