services:
  - type: web
    name: ExtService
    env: docker
    plan: free
    repo: https://github.com/TheMich157/ExtService
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://admin:admin@cluster0.wp3kmd1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/ExtService
      - key: API_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: trued
      - key: SCHEMA_VERSION
        value: "1"
      - key: ALLOWED_IPS
        value: ""
        value: "192.168.1.107,::1"


      

